sensor:
  #IC1 AddOn 2
  - platform: atm90e32
    cs_pin: 27
    phase_a:
      voltage:
        name: ${disp_name} Volts E
        id: ic5Volts
        accuracy_decimals: 1
      current:
        name: ${disp_name} CT13 Amps
        id: ct13Amps
      power:
        name: ${disp_name} CT13 Watts
        id: ct13Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:
      current:
        name: ${disp_name} CT14 Amps
        id: ct14Amps
      power:
        name: ${disp_name} CT14 Watts
        id: ct14Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:
      current:
        name: ${disp_name} CT15 Amps
        id: ct15Amps
      power:
        name: ${disp_name} CT15 Watts
        id: ct15Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    frequency:
      name: ${disp_name} Freq C
    line_frequency: 50Hz
    gain_pga: 1X
    update_interval: ${update_time}
  #IC2 AddOn 2
  - platform: atm90e32
    cs_pin: 17
    phase_a:
      voltage:
        name: ${disp_name} Volts F
        id: ic6Volts
        accuracy_decimals: 1
      current:
        name: ${disp_name} CT16 Amps
        id: ct16Amps
      power:
        name: ${disp_name} CT16 Watts
        id: ct16Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:
      current:
        name: ${disp_name} CT17 Amps
        id: ct17Amps
      power:
        name: ${disp_name} CT17 Watts
        id: ct17Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:
      current:
        name: ${disp_name} CT18 Amps
        id: ct18Amps
      power:
        name: ${disp_name} CT18 Watts
        id: ct18Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    frequency:
      name: ${disp_name} Freq D
    line_frequency: 50Hz
    gain_pga: 1X
    update_interval: ${update_time}

  - platform: total_daily_energy
    name: ${disp_name} CT13 kWh
    power_id: ct13Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
  - platform: total_daily_energy
    name: ${disp_name} CT14 kWh
    power_id: ct14Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
  - platform: total_daily_energy
    name: ${disp_name} CT15 kWh
    power_id: ct15Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
  - platform: total_daily_energy
    name: ${disp_name} CT16 kWh
    power_id: ct16Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
  - platform: total_daily_energy
    name: ${disp_name} CT17 kWh
    power_id: ct17Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
  - platform: total_daily_energy
    name: ${disp_name} CT18 kWh
    power_id: ct18Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
