name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: 6chan-factory.yaml
      name: 6chan-esphome
