name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: 6chan-noaddon-factory.yaml, 6chan-1addon-factory.yaml, 6chan-2addons-factory.yaml
      name: 6chan-esphome
